### ISSUE TITLE
Version string is incorrect

### ISSUE THREAD

**Issue by miketheman** [DapperDox/dapperdox#105]
Version [1.2.2 was released](https://github.com/DapperDox/dapperdox/releases/tag/v1.2.2) on March 8, 2018.

However, using this version today produces this message:

```
$ dapperdox -h 2>&1 | head -n1
2019/03/14 19:37:49 DapperDox server version 1.2.1 starting
```

This appears to be set here:

https://github.com/DapperDox/dapperdox/blob/e343254818a8c67c29de6b192e11b0fcb0703800/main.go#L45

However, the release process appears to use the branch/tag:

https://github.com/DapperDox/dapperdox/blob/e343254818a8c67c29de6b192e11b0fcb0703800/Makefile#L12

Using one or the other ought to help reconcile the difference.

**Comment by fenollp** [comment]
You should take a look at https://goreleaser.com/ ;)
