### ISSUE TITLE
Mimetypes set by consumes/produces are ignored

### ISSUE THREAD

**Issue by ralphvanetten** [DapperDox/dapperdox#37]
The global and per request `consumes` and `produces` properties are ignored. 

Dapperdox does not provide a way to select the mime type of data being send but always assumes data send is `"application/json"`.
It also does not provide a way to select the mime type of the data you want to receive. It seems to not touch the Accept header which in my case means it is set to `"text/plain, */*; q=0.01"` causing the server to return XML instead of JSON.

I would expect dropdowns listing the mimetypes listed in the consumes/produces to select what data is send/expected.

In swaggerui a dropdown is shown for selecting what the mime type is of the body send or the mime type of the expected result:

![selection_212](https://cloud.githubusercontent.com/assets/1533323/22505321/34dd7e3c-e87b-11e6-96bb-5090e44f4208.png)

![selection_213](https://cloud.githubusercontent.com/assets/1533323/22505342/4fc20268-e87b-11e6-9132-92ae8684cf21.png)

Minimal example:

```
{
  "x-navigateMethodsByName": true,
  "info": {
    "title": "minimal"
  },
  "swagger": "2.0",
  "host": "localhost:3123",
  "paths": {
    "/account": {
      "post": {
        "parameters": [ { "in": "body", "schema": { "type": "string", "title": "something" } } ],
        "summary": "post",
        "consumes": [
          "application/json",
          "application/json-patch+json"
        ],
        "produces": [
          "application/json",
          "text/xml"
        ],
        "responses": {
          "200": {
            "description": "Success",
              "schema": {
                  "title": "response",
                  "type": "string"
            }
          }
        }
      }
    }
  }
}

```

**Comment by zxchris** [comment]
Yes. We hadn't got that far, as our research suggested that most people were using JSON, so the explorer UI does not yet provide for the XML case.

Allowing the user of the explorer to specify the body MIME type and accepted response MIME type is in the works...

Will leave this issue open until it is released (which shouldn't be log, bugs take priority).

Thank you for the test cases.

**Comment by ralphvanetten** [comment]
We're not so interested in XML also, but the API just happens to prefer XML when not explicitly asking for JSON. I saw I can customize the APIexplorer and override the `Accept` header, so that would fix it for us.

I would be nice to be able to select between `application/json` and `application/json-patch+json` but as you say most people use JSON so it's not a huge issue.

Anyway, thanks again!

**Comment by zxchris** [comment]
Fixed in issue/37 merged into master. Release 1.1.0
