### ISSUE TITLE
api key name and location is ignored

### ISSUE THREAD

**Issue by ralphvanetten** [DapperDox/dapperdox#38]
The api key `name` and `in` options are ignored. Instead the api key is always added to the request using the query argument `key`

When having

```
 "securityDefinitions": {
    "some_key": {
      "type": "apiKey",
      "name": "myApiKey",
      "in": "header"
    }
  }
```

and

![selection_214](https://cloud.githubusercontent.com/assets/1533323/22506011/7285b5d0-e87e-11e6-9f5b-961a11292b85.png)

the key is not added as a header but as a query argument named `key`:

![selection_215](https://cloud.githubusercontent.com/assets/1533323/22506000/6306a8a8-e87e-11e6-994b-a085a80186ae.png)

After changing the security definition to use a query like so:

```
 "securityDefinitions": {
    "some_key": {
      "type": "apiKey",
      "name": "myApiKey",
      "in": "query"
    }
  }
```

the query argument `key` is still used and not `myApiKey`.

Minimal example to reproduce:

```
{
  "x-navigateMethodsByName": true,
  "info": {
    "title": "minimal"
  },
  "swagger": "2.0",
  "host": "localhost:3123",
  "paths": {
    "/account": {
      "get": {
        "summary": "list",
        "security": [ { "some_key": [] } ],
        "responses": {
          "200": {
            "description": "Success",
              "schema": {
                  "title": "response",
                  "type": "string"
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "some_key": {
      "type": "apiKey",
      "name": "myApiKey",
      "in": "query"
    }
  }
}
```

**Comment by zxchris** [comment]
This appears to be missed in the spec parsing. :-(
Of course, you can take complete control of api key passing etc through the APIexplorer javascript object [extensions](http://dapperdox.io/docs/explorer-customising) but you probably won't want to go that far! Besides, the "in" parameter should work!

Will fix.

**Comment by ralphvanetten** [comment]
Ah, yes, using APIexplorer extensions would be a more flexible solution in our case. I missed that part about customizing while reading the documentation. Thanks.

**Comment by zxchris** [comment]
Fixed in issue/38 merged into master. Release 1.1.0
