### ISSUE TITLE
`-document-rewrite-url` doesn't work as expected

### ISSUE THREAD

**Issue by ian-kent** [DapperDox/dapperdox#43]
From the documentation, it looks as though I should be able to do:
`-document-rewrite-url=from.url=to.url`
but this doesn't appear to have any effect on the `host` parameter in my `swagger.json` file, meaning the API explorer and endpoint URLs always show the original host

We can replace the host in the json file, but (with Docker) means building a new container for each environment, rather than customising it with environment variables

**Comment by zxchris** [comment]
Use `-spec-rewrite-url` that does what you want.
`-document-rewrite-url` changes the URL's found in the documentation (those pulled in from guides, overlays etc).
The combination of the two will allow you to have one container deployed in different environments (like moving from dev to test to live).
