### ISSUE TITLE
Loading specifications fails on Windows

### ISSUE THREAD

**Issue by zxchris** [DapperDox/dapperdox#45]
User has reported that they cannot load a JSON specification file; not even the petstore example that DapperDox provides.

The following steps outline the process that I followed.

Used Swashbuckle (with some configurations) to build a valid Swagger JSON file.
Installed Go and configured the necessary PATH variables.
Used Go to obtain dependencies and build DapperDox from source code.
Pointed DapperDox to my swagger.json file.

```
./dapperdox -spec-dir=C:\APIcodedir\output -spec-filename=swagger.json
```
The command returns the following error:
```
[XVlBzgbaiCMRAjWwhTHc] [info] GET /swagger.json (404, 0s)

Load specification error: could not access document at "http://localhost:3123/swagger" [404 Not Found]
```

I have tried specifying the `-spec-dir only` (without `-spec-filename`), in addition to using `-spec-filename` (without `-spec-dir`). All options result in the same 404 error. I tried specifying the petstore example that the DapperDox source includes, but same the error returns.

One of our developers tried this approach on his machine, which achieved the same results. Am I missing something? Any help is greatly appreciated!

**Comment by zxchris** [comment]
I think this is a path parsing / construction issue. Golang should transparently handle the difference between Microsoft and other OSes, so DapperDox may be confusing things.

I'm building a Windows VM so I can take a look.

**Comment by zxchris** [comment]
I've a hunch this is to do with how DapperDox manipulates the values of `spec-dir` and `spec-filename` to produce the served up specification paths, as it is not consistently using `filepath` functions.

Time to debug on windows.... ;-)

**Comment by lockewritesdocs** [comment]
@zxchris, I'm happy to help test on Windows when you're ready. Really eager to serve up some beautiful API docs :smiley:

**Comment by zxchris** [comment]
Precompiled x86 and amd64 releases with and example quick start .bat file, are available from http://dapperdox.io/download/downloads or https://github.com/DapperDox/dapperdox/releases
