### ISSUE TITLE
Provide an option to optionally ignore specifications which failed to load

### ISSUE THREAD

**Issue by akobyakov** [DapperDox/dapperdox#47]
Right now dapperdox fails if any of the specified specifications failed to load for any reason:
```golang
for _, specFilename := range cfg.SpecFilename {
	...
	err = specification.Load(specFilename, specHost)
	if err != nil {
		return err
	}
	...
}
```

Currently we are playing with a fork which loads specifications from multiple remote locations.

It would be really handy to have an option to skip specs which failed to load because of connectivity issues/syntax errors/timeouts/etc. That would also allow to avoid modifying a configuration every time one of the locations is failing.

**Comment by zxchris** [comment]
Seems like a good idea, particularly for development. I'm not sure you'd want to run with this option in production, except in exceptional circumstances (say a disaster-recovery situation).

Let me have a look at that.... ;-)

Chris

**Comment by zxchris** [comment]
Have a look at the next release candidate branch: https://github.com/DapperDox/dapperdox/tree/release/v1.2.0rc1

Does this meet your needs?

**Comment by akobyakov** [comment]
Awesome, looks exactly like what we wanted! 👍 
Thanks, Chris.

**Comment by zxchris** [comment]
Just to warn you that the v1.2.0rc1 branch will be in a state of flux until the next release, so for stability, you might want to stick to https://github.com/DapperDox/dapperdox/tree/issue/47, which is a branch off master (current stable release).
