### ISSUE TITLE
Reloading specifications

### ISSUE THREAD

**Issue by nick2705** [DapperDox/dapperdox#51]
Hi,

I am doing some evaluation with Win amd64 precompiled release.
I added some swagger.json for a new specification and it works OK.
I would like to be able to make changes in swagger.json, hit Refresh in browser and see them.
Is that even an option for now, or I need to stop/start every time when I have a change in spec files?

Regards,
Bojan

**Comment by zxchris** [comment]
Hi Bojan

You cannot currently do this - DapperDox parses the specifications and builds all the pages (and the URLs for them) in memory. It would be possible to do this in the future, but it is a lot of work behind the scenes. Interestingly, this also raises the question as how best to do this with remote specifications (`-spec-filename=http://.....`)

It's definitely a useful feature for developers, but probably isn't something you'd want to run in production (watching directories for example....)

It would be desirable to make the refresh happen without a service blip.

I'm going to mark this as a feature request!

**Comment by nick2705** [comment]
Thank you for fast reply. 
It is good to know what is possible for now.
I agree it is best if all is generated/cached on start, but would be great to have at least some mechanism that can be triggered from "outside" for restarting the server or invalidating cache, for deployment purposes.
If I go on Go side in next few weeks/months I would like to help with this.

Best regards!

**Comment by danbars** [comment]
+1 for this feature request.
Our use case is build process of many different projects (repositories) that generate a pile of swagger and markdown files in a centralized repository. We then have a script that git-pulls those files to a local folder on DapperDox server. 
So ideally every build process of one of those projects would generate the needed files, and then trigger a reload on DapperDox. 
Right now our only option is to restart DapperDox which results with a short blink. The more content that we have, this blink would become longer.
