### ISSUE TITLE
What does [: yield :] yield?

### ISSUE THREAD

**Issue by tlkiong** [DapperDox/dapperdox#55]
I am currently modifying the root page of this and I noticed there is `[: yield :]` in the `body.tmpl`.
I can't seem to trace what does this do. Please advice

**Comment by zxchris** [comment]
Se {{ yield }} in unrolled/render: https://github.com/unrolled/render
For historical reasons we changed the escaping in go's templates from {{ ... }} to  [: ... :] so where you see [: :] in DapperDox templates, you can read that as {{ }}.
