### ISSUE TITLE
Is it possible to support oneOf ?

### ISSUE THREAD

**Issue by ralphvanetten** [DapperDox/dapperdox#56]
Currently it seems using `oneOf` in the properties is not supported:

```
"properties": {
  "value": {
    "description": "A string or object",
    "oneOf": [ 
      {  
        "type": "string" 
      },
      {
        "type": "object",
        "properties": {
          "subvalue": {
            "description": "The string",
            "type": "string"
          }
        }
      }
    ]
  }
}
```

is rendered as:

![selection_263](https://cloud.githubusercontent.com/assets/1533323/25899075/bdc79a10-358e-11e7-910d-815ec90abf00.png)

I can imagine it will be difficult to render cleanly but I was wondering if it will be supported someday.
Thanks.

**Comment by zxchris** [comment]
Does Swagger/OpenAPI support `oneOf` now? It didn't: http://stackoverflow.com/questions/37713393/next-best-option-in-lieu-of-oneof-in-swagger-v2-0 and http://swagger.io/specification/#schemaObject

So long as it is supported by the [go-openapi](https://github.com/go-openapi) parser, then we can get it to work. There is an open issue about `allOf` not being completely supported by dapperdox, and we are rewriting the specification analysis to use more of `go-openapi`, which will improve, if not fix, the `allOf` compatibility.

**Comment by ralphvanetten** [comment]
Right, I forgot the Swagger/OpenAPI spec alters some of the JSON schema definitions. So I guess the answer is no and this issue can be closed.

**Comment by IntegrationMike** [comment]
Can we re-open this? Open API now supports oneOf but dapper does not appear to:
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

When I mimic that format:
```
"responses": {
  "200": {
    "description":"Text",
    "schema": {
      "oneOf":[
        {
          "$ref": "http://localhost:3123/definitions.json#/definitions/allowedParameters"
        },
        {
          "$ref": "http://localhost:3123/definitions.json#/definitions/calculatedPayment"
        }
      ]
    }
  },
}
```

I get 
Error: POST /api/vehicles/allowedParameters references a model definition that does not have a title member.

Thank you! 

Edit: Appears that oneOf is only valid for schema objects -- in this case, that's what I'm trying to do, so my case applies but the top level comment does not. I'll open a new Issue instead!
