### ISSUE TITLE
Theme and theme dir ignored from environment variable

### ISSUE THREAD

**Issue by bircow** [DapperDox/dapperdox#58]
Equivalent to `-theme` and `-theme-dir` commandline options should be `THEME` and 'THEME_DIR` environment variables. But I've found that Dapperdox ignores them (I run on 1.1.1-linux-amd64). Currently the only way to set these parameters are via commandline.

Sidenote: There's a typo in http://dapperdox.io/docs/configuration-guide - docs says `-themes-dir` and `THEMES_DIR` but actual option and environment name is in singular form (`-theme-dir` and `THEME_DIR`). I'm going to fix it myself.

**Comment by cpage-nexway** [comment]
Hello,

Here the beginning of my script used to run dapperdox:
`
export BIND_ADDR=0.0.0.0:8080
export REGISTRATION_ACTIVATE=true
export SITE_URL=http://api.nexway.staging.build/
export SPEC_DIR=/home/xxx/tmp/dapperdox/swagger
export THEME_DIR=/home/xxx/tmp/dapperdox/themes
#export AUTHOR_SHOW_ASSETS=true

DAPPERDOX_CMD='./nx-dapperdox
-spec-aggregate=true
-theme=my-theme
-log-level=debug
-force-specification-list=true
-spec-rewrite-url=http://localhost/
-assets-dir=./nexway/assets
-spec-file-detect=true'
`
As you can see i'm using THEME_DIR env var and -theme command line. it works fine for me.

**Comment by bircow** [comment]
I filed this issue too early. It seems it's something with my setup. Closing this issue. Ignore it. I'm sorry about it.
