### ISSUE TITLE
Add shebang to scripts

### ISSUE THREAD

**Issue by tomsaleeba** [DapperDox/dapperdox#64]
I found this when running the example but it probably applies to all your scripts.

Steps to reproduce:
1. download the binary (probably from http://dapperdox.io/download/downloads)
1. `cd /path/to/dapperdox-1.1.1.linux-amd64`
1. `./run_example.sh`

Expected behaviour:
It runs when using the FISH shell.

Actual behaviour:
The script *does* run in BASH but *doesn't* run using the FISH shell and an error message is printed:

        The file './run_example.sh' is marked as an executable but could not be run by the operating system.

I've been really specific here but this probably applies to your other scripts (`.sh`) in the repo and maybe to other non-bash shells. You can fix it by adding a shebang to the start of the scripts like:

        #!/usr/bin/env bash

I know it's not a big thing because you can always `bash <script name>` to run things and anyone who runs a non-bash shell probably understands how to run things.

Happy to create a PR if you'd like.

**Comment by zxchris** [comment]
Thanks, if you've already made the necessary mods - ping us a PR and we'll merge.

**Comment by tomsaleeba** [comment]
PR created: https://github.com/DapperDox/dapperdox/pull/69
