### ISSUE TITLE
TLS mode isn't working for me

### ISSUE THREAD

**Issue by SWSAmor** [DapperDox/dapperdox#71]
I did everything as in the docs, but

> ...
> 2017/09/04 13:15:21              ProxyPath: []
> 2017/09/04 13:15:21         TLSCertificate:
> 2017/09/04 13:15:21                 TLSKey:
> 2017/09/04 13:15:21 listening on 0.0.0.0:3123
> 2017/09/04 13:15:21 Registering specifications
> 2017/09/04 13:15:21 [XVlBzgbaiCMRAjWwhTHc] [info] GET /swagger.json (200, 115.9µs)
> 2017/09/04 13:15:22 Registering reference documentation
> 2017/09/04 13:15:22 Registering guides
> 2017/09/04 13:15:22 listening on 0.0.0.0:3123 for unsecured connections

Weird it seems DapperDox doesn't see the TLS files, but in the config:
> ...
>    -tls-certificate=/opt/dapperdox/dapperdox_rsa.crt \
>    -tls-key==/opt/dapperdox/dapperdox_rsa.key

Of course there are the files and readable by process owner. DapperDox is working but TLS. Is there any thing what i need to know? Thx.

**Comment by zxchris** [comment]
You have a `==` in the configuration example that you give. Is that a miss-type or a cut-n-paste error? DapperDox will error if you have this because it can't find file `=/opt/dapperdox/.....`

This is straight out of my local test:
```
-tls-certificate=/Users/chris/src/go/src/github.com/dapperdox/dapperdox.k/server.rsa.crt \
-tls-key=/Users/chris/src/go/src/github.com/dapperdox/dapperdox.k/server.rsa.key \
```
And gives me a config debug of:
```
2017/10/02 15:49:50              ProxyPath: []
2017/10/02 15:49:50         TLSCertificate: /Users/chris/src/go/src/github.com/dapperdox/dapperdox.k/server.rsa.crt
2017/10/02 15:49:50                 TLSKey: /Users/chris/src/go/src/github.com/dapperdox/dapperdox.k/server.rsa.key
```
If it cannot find one of the files (in this case the path is wrong) you get this debug:
```
2017/10/02 15:49:50              ProxyPath: []
2017/10/02 15:49:50         TLSCertificate: /Users/XXXX/src/go/src/github.com/dapperdox/dapperdox.k/server.rsa.crt
2017/10/02 15:49:50                 TLSKey: /Users/chris/src/go/src/github.com/dapperdox/dapperdox.k/server.rsa.key
```
And this failure:
```
2017/10/02 15:51:08 Error listening on 0.0.0.0:3123: open /Users/XXXX/src/go/src/github.com/dapperdox/dapperdox.k/server.rsa.crt: no such file or directory
```

So I think your start script is wrong - have you forgotten to put a `\` on the line *preceding* the `-tls-certificate=` line?

**Comment by SWSAmor** [comment]
The `==` was a cut-n-paste, but thx, I found it. I remarked this line:
`-spec-rewrite-url=petstore.swagger.io=PETSTORE.swagger.io \`
as
`#-spec-rewrite-url=petstore.swagger.io=PETSTORE.swagger.io \`
and that caused the trouble.
