### ISSUE TITLE
[Question] Open Specification Swagger in YAML?

### ISSUE THREAD

**Issue by AlexandreRoba** [DapperDox/dapperdox#72]
I could'nt find support for swagger in YAML. Is yaml supported? If not will it be? Thanks.

**Comment by washeck** [comment]
AFAIK YAML is not supported, only JSON at the moment. But you can use a simple script to convert it, e.g. this one: https://github.com/bircow/docker-dapperdox/blob/master/yaml_to_json.py

**Comment by AlexandreRoba** [comment]
thanks for the script. I'll give it a try.
