### ISSUE TITLE
Authentication for Web GUI

### ISSUE THREAD

**Issue by rajesh-balan** [DapperDox/dapperdox#73]
Would it be possible to associate a basic authentication (like user/pass credentials) for web site started  ? Our API specification is confidential and needs to be shared by the only users that has credentials.
Any work around also would be appreciated.

Thanks,
Rajesh Balan

**Comment by rajesh-balan** [comment]
Never mind that I installed NGINX and setup reverse proxy for authenticating through.

**Comment by zxchris** [comment]
Sitting behind nginx is certainly the easiest option - it is something that could easily be added to DapperDox, but would be of use to very few people, so hiding behind an authenticating proxy probably makes more sense.
