### ISSUE TITLE
Generate static files

### ISSUE THREAD

**Issue by greghrmweb** [DapperDox/dapperdox#74]
Is it possible to have the option to generate a static version (ie all the pages)? Deploying to an existing production database is complicated if we can't just generate the pages to serve up.

**Comment by greghrmweb** [comment]
No probs, thanks, already have the `wget` running, just wanted to know if I'd missed something.

**Comment by lfcipriani** [comment]
Thanks for Dapperdox and the wget workaround suggestion. Still it would be nice to consider it for next releases.

**Comment by murali474** [comment]
Hi,

@greghrmweb  can you share steps on how to  use wget to host static site of spec documentation?

**Comment by greghrmweb** [comment]
Hi @murali474, I have a bash script running that is essentially one command once you have dapperdox running:

`wget -q -r -p -F -k -nH -x -P ./dir_to_save_in -E -D localhost http://localhost:3123/`

you'll need to set `dir_to_save_in` to the right location and check that the localhost settings are correct for how you are running dapperdox (these work for a default running of it)

Once this runs, then the `dir_to_save_in` location should be full of static html files.
