### ISSUE TITLE
Response resources which are arrays don't indicate as such

### ISSUE THREAD

**Issue by JustASquid** [DapperDox/dapperdox#79]
Check out this part of the petstore example spec for operation `findPetsByStatus`:

```
 "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Pet"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid status value"
                    }
                },
```

Obviously this response returns an array of pets on success. However, in DapperDox itself, it simply shows that it will return `Pet`:

![Returns Pet](https://i.imgur.com/W8qJ4tO.png)

This is pretty confusing in my opinion. DapperDox should show that an array of resources is being returned here.

**Comment by zxchris** [comment]
This is fixed in the latest release v1.2.1, and on the master branch.

Response resources are suffixed with [] if an array of resources is returned.
A request body that takes an array resources is now correctly described.
